### ISSUE TITLE
SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104bfa024

### ISSUE THREAD

**Issue by celek** [CycloneDX/sbom-utility#75]
```
celek sbom-utility-v0.15.0-darwin-arm64 >> ./sbom-utility license list --input-file acdx.json --format csv
Welcome to the sbom-utility! Version `v0.15.0` (sbom-utility) (darwin/arm64)
============================================================================
[INFO] Loading (embedded) default schema config file: `config.json`...
[INFO] Loading (embedded) default license policy file: `license.json`...
[INFO] Attempting to load and unmarshal data from: `acdx.json`...
[INFO] Successfully unmarshalled data from: `acdx.json`
[INFO] Determining file's BOM format and version...
[INFO] Determined BOM format, version (variant): `CycloneDX`, `1.4` (latest)
[INFO] Matching BOM schema (for validation): schema/cyclonedx/1.4/bom-1.4.schema.json
[INFO] Scanning document for licenses...
[WARN] invalid SBOM: licenses not found (metadata.licenses) (acdx.json)
[WARN] invalid SBOM: licenses not found (metadata.component) (acdx.json)
[INFO] Outputting listing (`csv` format)...
License.Id,License.Name,License.Url,Expression,License.Text.ContentType,License.Text.Encoding,License.Text.Content
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104bfa024]

goroutine 1 [running]:
github.com/CycloneDX/sbom-utility/cmd.DisplayLicenseListCSV(0x140001d4380, {0x104ec1f28?, 0x14000110028?})
	/github/workspace/cmd/license_list.go:331 +0x514
github.com/CycloneDX/sbom-utility/cmd.ListLicenses({0x104ec1f28, 0x14000110028}, 0x0?, {0x0, 0x0, 0x0, {0x16b56f629, 0x9}, {0x0, 0x0}, ...}, ...)
	/github/workspace/cmd/license_list.go:248 +0x430
github.com/CycloneDX/sbom-utility/cmd.listCmdImpl(0x1400017ad00?, {0x1400012f580, 0x0, 0x4})
	/github/workspace/cmd/license_list.go:186 +0x1f0
github.com/spf13/cobra.(*Command).execute(0x140001e6000, {0x1400012f540, 0x4, 0x4})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x1051686e0)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/CycloneDX/sbom-utility/cmd.Execute()
	/github/workspace/cmd/root.go:279 +0x68
main.main()
	/github/workspace/main.go:96 +0x6c
```
[acdx.json.txt](https://github.com/CycloneDX/sbom-utility/files/14775140/acdx.json.txt)

**Comment by mrutkows** [comment]
@celek apologies for the delay after setting quite diff. expectations as my job changed shortly after receiving this.  Planning a point release asap with this fix.
